# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'MotionTracker' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MotionTracker

  pod 'Firebase/Core'
  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Core’
  pod 'PNChart'

  target 'MotionTrackerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MotionTrackerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
